__author__ = 'ashvini'

SOCIAL_AUTH_TWITTER_KEY = 'rSEVKnRX4zfj5Zoocs4ThnbrQ'
SOCIAL_AUTH_TWITTER_SECRET = 'FjWEXDgc279vW0JJx69O97KyktAzFtrOATLdz7PqXnUzqO9Tz7'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_LOGIN_URL = '/'